### PR TITLE
Added jshint gulp task and cleaned up all warnings/errors

### PR DESCRIPTION
**Pull request by dougmartin**
Also removed calculator.jsx since it is not needed (no sense cleaning it up and then deleting it).  

NOTE: jshint runs over the .jsx file after they are transformed by gulp-react so the error messages show .js extensions instead of .jsx for the files

### CODE REVIEW

**Comment by dougmartin** [comment]
Hold off on this.  I think I found a regression in this commit.

**Comment by dougmartin** [comment]
Ok I have the regression fixed.  I removed the requirement for === in jshint because we have a fair number of int comparions to stringified ints from Firebase in the code.  I'm going to clean up the commit history next so there isn't the duplicate merge.

**Comment by dougmartin** [comment]
This is now good to go.  I removed the triple equal requirement in jshint as we do a fair bit of int comparisons to stringified ints from Firebase in the code.

**Comment by sfentress** [comment]
Looks great.

**Pull request merged**
