### PR TITLE
Added editor for activity JSON

### PR DESCRIPTION
**Pull request by dougmartin**
I've added an online editor for the activity JSON.  The editor can save the JSON in the browser's local storage and the teaching-teamwork app has been updated so that activity name's prefixed with 'local:' load from local storage instead of the file system.

You can see it in operation here without pulling down the code:

http://dougmartin.github.io/concord/teaching-teamwork/add-editor/editor/

This wasn't in the SOW but I thought that it could save everyone (especially me) a lot of time generating JSON when testing new components or debugging existing components.  The editor has a built in "linter" so when you have invalid JSON it will show a red X on the left hand gutter of the editor.  

To test it out:

1. Open the link above
2. Either create a new activity or paste in the activity from the activities folder in the code
3. Click the 'Save' button to save the activity (if the save button isn't enabled after the paste enter a space in the editor - sometimes pastes don't register as a change)
4. Click the 'Use' button to open the activity in teaching-teamwork in a new tab 

Anything you 'save' will only be saved in your browser - others won't be able to see it.  If you clear your browser history the saved files will also be cleared.  Until then you can use the 'Open' button which will list the saved files - just double click on a filename to open it.

### CODE REVIEW

**Comment by sfentress** [comment]
This looks like you took great initiative. I know that this will be the start of making authoring much easier for folks.

I have one main code change, and then a proposal for further changes -- which hopefully won't look like bikeshedding this feature you created.

The main one is to not check in all the CodeMirror source directly, but to use Bower: https://github.com/codemirror/CodeMirror/blob/master/bower.json

This will not only keep our source cleaner but make it easier to update CodeMirror when needed.

For the proposed further change, while we could just bring it in as-is (since by itself it already makes it easier for people who aren't running the code locally), tell me how hard you think it would be to add the following:

Currently, it takes several steps to iterate through changes when an author is trying to create an activity (which typically involves many small changes): After they've written a new activity, they clicked Save, name it, click Use, see the activity working, and then they need to switch back to the editor tab to make changes, click Save, switch back to the viewer, and hit reload. While it's not onerous, it could be faster. (For people running the app locally, for instance, any change they save to the JSON file is instantly reflected in the browser, without having to do anything else.)

How hard to you think it would be to display this instead as pop-up pane, in the same window as the TT activity? They would then need three buttons: the most prominent, Update, would update the activity immediately, without ever needing to save anything, and without needing to switch tabs. Save and Load would then be there when the author was happy with their activity.

This would work like jsFiddle: nothing needs to be saved (you just hit "Run"), and everything happens in the same window.

Starting from that base, it would then be much easier to iterate on further features, like the ability to edit the breadboard by hand (dragging components) and instantly updating the circuit json in the editor panel. (Like [this](http://concord-consortium.github.io/breadboard/loading-serializing-logging.html).) This wouldn't be possible if it were in another tab.

A further benefit of that is that it would introduce the concept of an authoring mode, and so allow us to do things in the future like skipping the login popups on reload when editing (although circuit selection would still be needed), and not logging anything to the Log Manager.

Do you think making this an in-activity pop-up pane (made visible by something in the url, presumably) would be hard to add?

@phrwtz do you think the changes described are worth it, or would you prefer to get what Doug has into production immediately? (Although note it's already in "production" as you can just use it at Doug's site.)

**Comment by dougmartin** [comment]
I think leaving the editor in its own page makes more sense - mainly because the editor UI would not fit into a new pane in the app very well.  I have some more UI ideas for the editor, like a right hand sidebar that would show common JSON snippets so you could copy and paste them into the editor or click a button to insert them at the current cursor position.

Instead we can add an 'Update' button in the editor that would only activate once the 'Use' button had been clicked.  The update button would use postMessage to tell the app to reload but skip the user login. We could also add an 'Edit' button to the app that would load the editor and send it the contents of the JSON via postMessage.  The editor would then enable the 'Update' button so any editor changes you make would be reloaded in the app.

I'll add a commit to move the CodeMirror code into bower and update the gulp script to copy it to dist.  I'll hold off doing anything else until there is a consensus.

**Comment by phrwtz** [comment]
Sorry for the late entry -- I was out getting physical therapy for my shoulder and have only now had a chance to play with this shiny new toy. Reactions:

First of all, thank you, Doug, for taking the initiative to do this. As you know, making life easier for you also makes it easier for the rest of us. Frankly, I had left anything to do with authoring out of the SOW, not because I thought it was unimportant, but because in the grand scheme of things we could live with a cumbersome system but we couldn't live without certain enhancements (like the calculator) that were necessary before we could try things out with students.

Reactions to the system itself -- it certainly makes it much more straightforward to do local editing. Sam's suggestions for simplifying still further the updating of existing scripts are all very relevant. The exact details aren't all that important (e.g., if there's a problem with screen real estate then it's fine to have the editor in a separate page). It's not all that critical, btw, to eliminate the user login step when the user is in authoring mode since we're going to have to specify the circuit anyway (but if it's easy to do you might as well do it). More important, most likely, would be to eliminate unnecessary logging of data. The idea of adding "gestural" authoring has been around as long as we've had the gestures themselves (i.e., draggable components). It would certainly simplify things tremendously (but only for those things that are in the GUI in the first place). Sam has a produced a demo site at http://concord-consortium.github.io/breadboard/loading-serializing-logging.html that does some of this.

That leaves the important question of how to support more the "publishing" of the authored product -- either to a relatively private staging area or to the public at large. It would be Really Nice if that could be accomplished as easily as the current system allows temporary "show as you go" updates. For instance, uploading to the staging area ought to be a simple as clicking on a "Publish" button, no? Full out and out exposure to the world at large ought to continue to require some sort of permission, but otherwise should appear to the author as just a different way to "save."

By the way, I've posted two simple activities at

http://dougmartin.github.io/concord/teaching-teamwork/add-editor/#local:Test external battery on buses

and

http://dougmartin.github.io/concord/teaching-teamwork/add-editor/#local:Test external battery direct to board

Try them by measuring the voltage between the black wire, which comes from the battery, and, variously, both ends of the red wire and both ends of the resistor. You'll find that in the first case (external battery attached to the two power buses on the breadboard) you get the full battery voltage of 12.5 volts between the black wire and the near end of the red wire, but zero volts at the other end of that wire! In other words, the circuit behaves as though 12.5 volts are developed across a (zero resistance) wire (though if you measure the voltage across that wire directly you get 0 volts, as you should). Note, too, that with the battery-to-power-bus circuit, if you disconnect the resistor from the red wire, everything works fine. And the other circuit, in which the external battery is connected to the top row of holes on the breadboard, works fine as well.

Final question: if I log out of Chrome I'll lose those two circuits, right? So how do I make them permanent?

Sorry for the long note! Good work, Doug!

**Comment by dougmartin** [comment]
Paul: currently the data is stored in local storage which is local to your machine so I can't see those two activities - they only exist in your browser's storage.  Local storage is persistent across logins and power cycles  - it is only deleted if you clear your browser data.

If you could email me those two configs I can try them locally.

We could use Firebase for the storage system to enable publishing.  This would require us to add an authentication layer which is pretty easy to do in Firebase using various 3rd party login providers (https://www.firebase.com/docs/web/guide/user-auth.html).  Each activity would then be "namespaced" with the users name so it would look something like: "#remote:dougmartin/demo-test".  The authentication would prevent users from overwriting other user's data - we could still allow browsing of other people's files but not saving over them.

**Comment by sfentress** [comment]
I do think that it would be quite possible to put it on the same page as the breadboard -- using any of (1) a editing-mode view of the page which eliminates all the whitespace and puts the model at the top, or on the side (the editor only needs ~500px across) or (2) using a draggable, collapsable editor.

However, I don't think it's so critical that it means not using the editor.

I do think we'll eventually want an in-page editor to allow easy wysiwyg editing of the breadboard components, so I'd only be wary if the additional code required to support this on a separate page (postMessage) ended up taking much time, as it might eventually be rolled back.

**Comment by phrwtz** [comment]
On Thu, Mar 5, 2015 at 1:47 PM, Doug Martin <notifications@github.com>
wrote:

> If you could email me those two configs I can try them locally.


​Here's the one with the bug

{
  "name": "Test external battery on buses",
  "externalComponents": [
    {
      "type": "battery",
      "UID": "source",
      "voltage": 12.5,
      "connections": "battery_1,battery_2"
    },
    {
      "type": "wire",
      "connections": "battery_1,0:off_10",
      "hidden": true
    },
    {
      "type": "wire",
      "connections": "battery_2,0:off_11",
      "hidden": true
    }
  ],
  "clients": [
    {
      "show_multimeter": true,
      "circuit": [
        {
          "type": "wire",
          "connections": "off_11,left_positive21",
          "draggable": true
        },
        {
          "type": "wire",
          "connections": "off_10,left_negative21",
          "draggable": true
        },
        {
          "type": "wire",
          "connections": "a15,left_positive5",
          "draggable": false
        },
        {
          "type": "resistor",
          "UID": "r1",
          "label": "R1",
          "resistance": "100",
          "connections": "c15,c27",
          "hidden": false,
          "draggable": true
        }
      ]
    }
  ]
}

And this is the one that works:

{
  "name": "Test external battery direct to board",
  "externalComponents": [
    {
      "type": "battery",
      "UID": "source",
      "voltage": 12.5,
      "connections": "battery_1,battery_2"
    },
    {
      "type": "wire",
      "connections": "battery_1,0:off_10",
      "hidden": true
    },
    {
      "type": "wire",
      "connections": "battery_2,0:off_11",
      "hidden": true
    }
  ],
  "clients": [
    {
      "show_multimeter": true,
      "circuit": [
        {
          "type": "wire",
          "connections": "off_11,a15",
          "draggable": true
        },
        {
          "type": "wire",
          "connections": "off_10,a27",
          "draggable": true
        },
        {
          "type": "resistor",
          "UID": "r1",
          "label": "R1",
          "resistance": "100",
          "connections": "c15,c22",
          "hidden": false,
          "draggable": true
        }
      ]
    }
  ]
}

**Comment by dougmartin** [comment]
Hi Paul,

You should open an issue for the off screen battery bug and put the configs there - that way we can track any changes needed against it.

**Comment by phrwtz** [comment]
I was going to do that (it's called a "complaint" isn't it?) but I've
forgotten how!

Paul


Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

"Lead us not into temptation – just tell us where it is, we'll find it."

            Sam Levenson

**Comment by dougmartin** [comment]
You can create a new issue for the project here:

https://github.com/concord-consortium/teaching-teamwork/issues

**Comment by dougmartin** [comment]
I've added a few buttons to the editor usable here:

http://dougmartin.github.io/concord/teaching-teamwork/add-editor/editor/

1. Format - formats the JSON to a nice pretty form
2. Validate - validates that the JSON syntax is correct
3. Use Local - uses locally saved activity, formally 'Use'
4. Login/Logout - login using Firebase (I'll send the credentials in a separate private email)
5. Publish - publish an activity to Firebase (when logged in)
6. Use Remote - use the published activity on Firebase (when logged in)

Published (remote) activities have the following form in the app url:
"#remote:*username*/*filename*" where username is the username of your email address, so for example: "#remote:doug/sample-activity".

This pull request should not be merged.  Instead I'd like to integrate the editor into the app - I'm thinking a button on the lower right that when clicked shows the editor in a pane across the lower part of the screen with a spliter so it can be resized.  I need to wait until the add-notes pull request is merged since I changed a lot of the app structure.  Once that is in place I can add the editor to the page and then add:

1. A real login dialog (instead of the prompts)
2. A way to browse and open remote activities
3. Security rules on Firebase to isolate activity saves per user so user A can't ovewrite user B.

**Comment by sfentress** [comment]
A request: if it's not too much work, when you think this PR is ready for pulling, could you first rebase the changes so that the final changes are clearly described by the commits?

I'm assuming that, since the feature has changed over time, there's going to be some back-tracking and changes in the commits, and it would be great to remove the noise and get a clear commit story.

(If it's a pain, don't worry about it.)

**Comment by dougmartin** [comment]
I don't think this branch should be merged.  I'd like to integrate the editor into the page and when the add-notes branch there were a lot of changes to the React structure.  I think it would be best to create a new branch with the integrated editor now that the add-notes branch has been merged.

**Comment by sfentress** [comment]
Closing the obsolete PR, which is replaced by #9

**Pull request closed without merging**
