### PR TITLE
Add view other circuits

### PR DESCRIPTION
**Pull request by dougmartin**
This is a rather big commit that adds a view of all the circuits.  This commit depends on the breadboard PR (https://github.com/concord-consortium/breadboard/pull/4) to be live (and bower updated) to enable the new probeDropped event to track probe movements when the probe does not snap to a component.

### CODE REVIEW

**Comment by dougmartin** [comment]
@sfentress Could you review this?

**Comment by dougmartin** [comment]
@sfentress Wait on this - I need to remove the new "fixedCircuit" code because leads need to be able to be picked up.

**Comment by dougmartin** [comment]
Updated with work from this morning.

**Comment by sfentress** [comment]
:+1: This all looks fine to me, with the proviso about how ignoring external components connected to ghost holes may not be viable in the future.

I can merge this in.

**Pull request merged**
