### PR TITLE
Removed remote event tracking in solo mode and fixed race condition [#104025902]

### PR DESCRIPTION
**Pull request by dougmartin**

### CODE REVIEW

**Comment by phrwtz** [comment]
I didn't realize there was a race condition. Was this only in the solo
version?

Paul


Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

**Comment by dougmartin** [comment]
This race condition in new due to the change where we no longer prompt for the username if it is the cookie.  In group mode we wait for either the group name or to confirm the group membership.  In solo mode that is skipped and the circuit is loaded without the breadboard view being created which causes the components not to be added.  The new code waits for the breadboard view to exist before loading (< 50ms wait).

**Comment by dougmartin** [comment]
The reason for the delay in the breadboard view creation is the time it takes to load and build the svg breadboard image.

**Comment by phrwtz** [comment]
Makes sense.

Paul


Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

**Comment by sfentress** [comment]
In Sparks the SVG view can notify listeners when it has loaded. You can see this in `activity-view.js:43`, where we call `breadboardView.ready` with a callback function.

I forget whether we have easy access to a reference to the SVG view in TT, but if we do, would that make this more robust? Or are we guaranteed that the view will have rendered in 50ms even on slower computers?

**Comment by phrwtz** [comment]
I thought Doug was waiting for some signal that the view had loaded. Doug?

Paul


Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

**Comment by dougmartin** [comment]
The new code doesn't wait a defined 50ms interval - that was just the time I was seeing when I added the code to wait for the breadboardView to become initialized.  Here is the new code - it checks at 10ms intervals if the breadboardView is available and when it is is continues with the callback.  There is code in sparks insertComponent() that checks if the breadboardView is initialized with this same if check:

            waitForBreadboardView = function (callback) {
              var check = function () {
                if (sparks.workbenchController.breadboardView) {
                  callback();
                }
                else {
                  setTimeout(check, 10);
                }
              };
              check();
            }

**Comment by phrwtz** [comment]
Interesting! So you don't have to set up a special event for the breadboard
to announce that it's there, you just have to invoke the breadboardView? I
would have thought that you would get an error if the view didn't (yet)
exist, but evidently you can treat that as a return of "false"...

Of am I missing something?

Paul


Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

**Pull request merged**
