### PR TITLE
Added query string flag of 'no-activity' to skip loading the activity

### PR DESCRIPTION
**Pull request by dougmartin**
For easier debugging (by not having to enter your name and group) a query string flag of 'no-activity' can be used.  The code just checks for its presense, not its value like this ?no-activity/

### CODE REVIEW

**Comment by sfentress** [comment]
Hmmm, I think a better solution might simply have been to remove the default activity. So if you go to concord-consortium.github.io/teaching-teamwork/ then no activity would load.

I think the default activity was useful when folks were just trying this out, but by now all our authors and testers will want to be going to a specific activity, or to no activity, so there isn't much point any more in the default.

**Comment by phrwtz** [comment]
I agree. FWIW, having the Two Resistors activity come up by default is a
pain -- particularly so because I have to log on and choose a circuit
before I can blow it away and do what I wanted to do in the first place.
When you're using the editor the default should be no-activity.

Paul


Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

"Lead us not into temptation – just tell us where it is, we'll find it."

            Sam Levenson

**Comment by dougmartin** [comment]
Looks like I merged too quickly.  Do you want me to remove this and the default activity?

**Comment by phrwtz** [comment]
I think that would work, yes.

In the meantime, I'm still looking at the log files and seeing lots of room
for small changes that might make it a lot easier to parse the things. For
example, do you understand why detaching a probe gives such a huge readout?

{"color"=>"red", "location"=>"{\"ancestorOrigins\"=>{\"length\"=>0},
\"origin\"=>\"http://concord-consortium.github.io\",
\"hash\"=>\"#three-resistors-solo-v1\", \"search\"=>\"\",
\"pathname\"=>\"/teaching-teamwork/\", \"port\"=>\"\", \"hostname\"=>\"
concord-consortium.github.io\", \"host\"=>\"concord-consortium.github.io\",
\"protocol\"=>\"http:\", \"href\"=>\"
http://concord-consortium.github.io/teaching-teamwork/#three-resistors-solo-v1\
"}"}

Paul


Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

"Lead us not into temptation – just tell us where it is, we'll find it."

            Sam Levenson

**Pull request merged**
