### PR TITLE
Add basic calculator

### PR DESCRIPTION
**Pull request by dougmartin**
Adds a basic calculator with +, -, *, /, backspace, inverse, square root and plus/minus.

As per the SOW I adapted it from an existing calculator.  I chose this one:

http://thecodeplayer.com/walkthrough/javascript-css3-calculator

The adaptation included converting it to React and adding backspace, inverse, square root and plus/minus.

I placed the calculator 50 pixels from the top right corner for now.

### CODE REVIEW

**Comment by phrwtz** [comment]
How can I see this in action? Is there an interface for accessing the calculator from within a Teaching Teamwork activity? Regardless, I assume that the calculator doesn't log yet, right? Do you understand how to make it do that?

**Comment by dougmartin** [comment]
There is an interface - a button in the top right corner.  It doesn't log anything yet.

Here are the instructions for checking out the pull request locally so you can see the changes:

https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by phrwtz** [comment]
Thanks, Doug!

paul


Paul Horwitz
The Concord Consortium
25 Love Lane
Concord, MA  01742

978-405-3223 (office)
978-369-4935 (home)
978-505-5401 (cell)
978-405-2078 (fax)

"Lead us not into temptation – just tell us where it is, we'll find it."

            Sam Levenson

**Comment by sfentress** [comment]
This looks very good. One small improvement would be the ability to drag it around, so that it didn't cover up the DMM/OScope on smaller screens, but that isn't necessary for now.

However, logging is necessary from the start, as that's the main reason for the built-in calculator. Could you hook this into the logging controller so that we can log what the users does with it?

This should log both the low-level and high-level events -- that is, button clicks as well as events that capture the bigger interaction: making a calculation.

The exact event names are arbitrary, but I would log an "opened calculator" and "closed calculator" event (with no parameters), a "pressed calculator button" event on each push of a button, with the value of the button, and an event describing the calculation performed when any of the green buttons are pressed, e.g.

    "Calculation performed",
    {
        "calculation": "5+7",
        "result": 12
    }

The high-level event should be reproducible from the low-level events alone (i.e. the low-level events should provide complete data), but the high-level event should be useful for working out what the student did without the low-level ones.

**Comment by dougmartin** [comment]
Ok, I'll add the dragging and the logging tomorrow.

**Comment by dougmartin** [comment]
Ok, I've added dragging and logging to the calculator.  One note: while testing I saw a lot of 500 errors on the Heroku app that is doing the logging.

**Comment by sfentress** [comment]
Do you see 500 errors on all events, or just on some of them? When I view the live site and open the XHR tab in the Network console, I see many good (201) posts.

Currently at the Log Manager site I'm seeing two events getting logged: "Opened calculator" and "Cleared calculator"

**Comment by dougmartin** [comment]
I'm seeing errors for the events I log that have an event_value.  The event_values are objects - should I be serializing them to a string first?

image

**Comment by sfentress** [comment]
The logEvent signature is `logEvent(eventName, value, parameters)`.

`values` is a simple value (string, bool, or number), `parameters` is an object. You can have one, both or neither. If you just want to log parameters, you would use `logEvent(eventName, null, {params})`

You can feel free to add a comment above log.js:logEvent making this clear.

Looking at your logs, I would log anything that you're using an object for as the parameters argument, with no need for a value argument.

**Comment by dougmartin** [comment]
Sorry, I should have caught that. I was going off the logEvent() calls in chat.jsx.  I've updated the code and added a note in log.js

**Pull request merged**
