### PR TITLE
Replaced calculator with "MathPad"

### PR DESCRIPTION
**Pull request by dougmartin**
Replaced simple calculator with new "MathPad" component.

### CODE REVIEW

**Comment by sfentress** [comment]
Two small comments:

1. The definitions of all the constants and functions as straight HTML are very verbose. What would you think of just making a definitions object and then looping through it? e.g.

    {
       "e, E": "Euler's number, the base of the natural logarithm.",
       "LN2": "Returns the natural logarithm of 2."
       ...
    }

that would make the code tighter and easier to edit/update definitions.

2. Any reason to keep calculator.jsx? If we decide we want it back it can be found in git.

**Comment by dougmartin** [comment]
I originally had them in an object when I was building my own context for eval (I used the object both to populate the context and to build the help) but I converted it to straight html (and converted the component to JSX) so that the help could be edited in html to allow more formatted text easily in the future.

I did remove calculator.jsx on a susequent commit after I squashed everything to create this pull request but I messed up a rebase/push on my fork and I didn't want to pollute the history (you can see what happened here:)

https://github.com/dougmartin/teaching-teamwork/commits/math-scratchpad

**Comment by dougmartin** [comment]
Let's just merge this one and I'll do a cleanup pull tomorrow to remove the calculator on another branch.

**Comment by sfentress** [comment]
I'll merge it in now, then, not being quite clear from your branch what happened.

I do still think that it would be better without the HTML redundancy (the json definition could easily include html, so that formatting shouldn't be an issue), but that could be done at the same time as removing the old calculator view.

**Pull request merged**
